version: '3.7'

networks:
  kafka-net:
    name: kafka-net
  zk-net:
    external: true

services:

  kafka1:
    image: wurstmeister/kafka:2.12-2.4.1
    restart: always
    container_name: kafka1
    ports:
      - "9093:9092"
    external_links:
      - zk1
      - zk2
      - zk3
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: 172.16.11.130                   ## 修改:宿主机IP
      KAFKA_ADVERTISED_PORT: 9093                                 ## 修改:宿主机映射port
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.2.14:9093    ## 绑定发布订阅的端口。修改:宿主机IP
      KAFKA_ZOOKEEPER_CONNECT: "zk1:2181,zk2:2181,zk3:2181"
    volumes:
      - "/storage/data/kafka1:/kafka"
    networks:
      - kafka-net
      - zk-net


  kafka2:
    image: wurstmeister/kafka:2.12-2.4.1
    restart: always
    container_name: kafka2
    ports:
      - "9094:9092"
    external_links:
      - zk1
      - zk2
      - zk3
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_HOST_NAME: 172.16.11.130                 ## 修改:宿主机IP
      KAFKA_ADVERTISED_PORT: 9094                               ## 修改:宿主机映射port
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.2.14:9094   ## 修改:宿主机IP
      KAFKA_ZOOKEEPER_CONNECT: "zk1:2181,zk2:2181,zk3:2181"
    volumes:
      - "/storage/data/kafka2:/kafka"
    networks:
      - kafka-net
      - zk-net

  kafka3:
    image: wurstmeister/kafka:2.12-2.4.1
    restart: always
    container_name: kafka3
    ports:
      - "9095:9092"
    external_links:
      - zk1
      - zk2
      - zk3
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_HOST_NAME: 172.16.11.130                 ## 修改:宿主机IP
      KAFKA_ADVERTISED_PORT: 9095                              ## 修改:宿主机映射port
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.2.14:9095   ## 修改:宿主机IP
      KAFKA_ZOOKEEPER_CONNECT: "zk1:2181,zk2:2181,zk3:2181"
    volumes:
      - "/storage/data/kafka3:/kafka"
    networks:
      - kafka-net
      - zk-net

  kafka-manager:
    image: kafkamanager/kafka-manager:3.0.0.4
    restart: always
    container_name: kafka-manager
    hostname: kafka-manager
    ports:
      - "9000:9000"
    links:            # 连接本compose文件创建的container
      - kafka1
      - kafka2
      - kafka3
    external_links:   # 连接本compose文件以外的container
      - zk1
      - zk2
      - zk3
    environment:
      ## 修改:宿主机IP
      ZK_HOSTS: zk1:2181,zk2:2181,zk3:2181
      TZ: CST-8
    networks:
      - kafka-net
      - zk-net