version: '3.3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db-dev'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'dev'
      MYSQL_PASSWORD: 'dev123456'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '1qaz2wsx'
    ports:
      - '3306:3306'
    expose:
      - '3306'
      # Where our data will be persisted
    volumes:
      - /storage/data/mysql:/var/lib/mysql
    command: [
              '--character-set-server=utf8mb4',
              '--collation-server=utf8mb4_unicode_ci',
              '--default-time-zone=+8:00'
             ]
